# Generated by Django 4.0.5 on 2022-06-07 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
