# Generated by Django 4.0.5 on 2022-06-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='service',
            new_name='company',
        ),
    ]
