# Generated by Django 4.0.5 on 2022-06-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_service_rating_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='operation_area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
