# Generated by Django 4.0.4 on 2022-05-05 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleaning_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[('VERY_BAD', 1), ('BAD', 2), ('MEDIUM', 3), ('GOOD', 4), ('VERY_GOOD', 5)])),
                ('company', models.ManyToManyField(to='cleaning_company.company')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
