# Generated by Django 4.0.4 on 2022-05-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_review', '0002_remove_review_user_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('Very bad', 'Very Bad'), ('Bad', 'Bad'), ('Medium', 'Medium'), ('Good', 'Good'), ('Very  good', 'Very Good')], max_length=20),
        ),
    ]
