# Generated by Django 4.0.4 on 2022-05-12 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0008_alter_company_date_foundation'),
        ('rating_review', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='company',
        ),
        migrations.AddField(
            model_name='review',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cleaning_company.company'),
            preserve_default=False,
        ),
    ]
