# Generated by Django 4.0.4 on 2022-05-05 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('operation_city', models.CharField(max_length=50)),
                ('date_foundation', models.DateField(default=datetime.date(2022, 5, 5))),
                ('services', models.ManyToManyField(to='service_type.service')),
            ],
        ),
    ]
