# Generated by Django 4.0.4 on 2022-05-11 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_foundation',
            field=models.DateField(default=datetime.date(2022, 5, 11)),
        ),
    ]
