# Generated by Django 4.0.4 on 2022-05-11 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0005_alter_company_date_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_foundation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
