# Generated by Django 4.0.4 on 2022-05-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0007_alter_company_date_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_foundation',
            field=models.DateField(auto_now=True),
        ),
    ]
