# Generated by Django 4.0.4 on 2022-05-23 11:37

from django.db import migrations, models
def create_cars(apps, schema_editor):
    Car = apps.get_model('car', 'Car')
    cars=[
        {"title":"Toyota", "description":"Japanese  car","speed":123.34},
         {"title":"BMW", "description":"German  car","speed":433.34},
           {"title":"Mercedes", "description":"Elite car","speed":563.34},
             {"title":"NIssan", "description":"Korean  car","speed":563.34},
             {"title":"Pigoud", "description":"French car","speed":453.34},
             {"title":"Ferari", "description":"Italian  car","speed":303.34},
             {"title":"Bugatti", "description":"Italian car1","speed":563.34},
    ]
    for i  in  range(0,len(cars)):
        Car.objects.create(title=cars[i]['title'],description=cars[i]['description'],speed=cars[i]['speed'])

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('speed',models.DecimalField(decimal_places=2, max_digits=6))
            ]
        ),
        migrations.RunPython(create_cars)
    ]
