# Generated by Django 4.0.5 on 2022-06-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(1, 'Read'), (0, 'Not Read')], default=0),
        ),
    ]
