# Generated by Django 4.0.5 on 2022-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sent'), (0, 'Not Sent')], default=0),
        ),
    ]
