# Generated by Django 4.0.5 on 2022-06-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('measurement_unit', models.CharField(choices=[('per meter  square', 'Square Meter'), ('per  hour', 'Hour'), ('per kg', 'Kilogramm')], max_length=30)),
                ('per_unit_price', models.FloatField()),
                ('descriptive_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('company', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='company.company')),
            ],
        ),
    ]
