# Generated by Django 4.0.4 on 2022-05-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
           [
               ( "CREATE  TABLE IF NOT EXISTS `products`(`id` INT NOT NULL  ,`title` VARCHAR(255) NULL ,`description` TEXT NULL ,`price` DECIMAL(4,2) NULL, PRIMARY KEY (`id`) )"),
               ("ALTER  TABLE products ADD image VARCHAR(255) NULL "),
           ]
        )
    ]
